apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: default
  annotations:
     kubernetes.io/ingress.class: "nginx"
     ingress.kubernetes.io/add-base-url: "true"
spec:
  tls:
  - hosts:
    - chatserver.com
    secretName: tls-secret
  rules:
  - host: chatserver.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: flask-service
              port: 
                number: 5000 
        - path: /room
          pathType: Prefix
          backend:
            service:
              name: room-service
              port: 
                number: 5000